### PR TITLE
Polish project README

### PR DESCRIPTION
**Pull request by semioticrobotic**
This pull requests suggests several changes aimed at enhancing readability of the project's README file. Specifically, it:

* Removes duplicative subheadings
* Removes outdated references
* Re-writes the project description to enhance clarity
* Establishes a one-line-per-sentence convention
* Removes several Markdown errors

### CODE REVIEW

**Comment by semioticrobotic** [comment]
Assigning to @LauraHilliger, kindly seeking review and merge.

**Review by LauraHilliger — APPROVED** [review]
Thanks so much for taking real time with this! Looks great, though I think I have a link I need to dig up for the P4 example – the wiki was shut down years ago. Will have a look!

**Comment by LauraHilliger** [comment]
Ah, @jimmysjolund or @semioticrobotic one of you will need to merge, I don't have write access in this repo.

**Comment by semioticrobotic** [comment]
Thanks, @LauraHilliger! Always happy to add additional links to keep our examples fresh and relevant.

**Comment by jimmysjolund** [comment]
We should check that. I thought I had set all Ambassadors as Owners or Maintainers?

**Comment by semioticrobotic** [comment]
> We should check that. I thought I had set all Ambassadors as Owners or Maintainers?

Just did. Ambassadors were indeed added as collaborators, but only with `Read` permissions. They now have `Maintainer`.

**Pull request merged**
